### ISSUE TITLE
Can we swap out of python for golang ?

### ISSUE THREAD

**Issue by gedw99** [andreas-gone-wild/snackis-golang#1]
Will make it easier to get going and also allow building mobile clients with go.

There are plenty of good IMAP and SMTP libs in golang.

**Comment by andreas-gone-wild** [comment]
I found the std smtp lib and available imap libs to have weird concurrency issues. If someone else wants to have a go then I'll be happy to have a look. But for now, I don't have any time over to mess around with this myself.

**Comment by joeblew99** [comment]
i will have a looksie

**Comment by andreas-gone-wild** [comment]
Cool, scripts/imap.py/smtp.py should work well as templates for the functionality needed. Let me know if there is anything I can do to help.

**Comment by andreas-gone-wild** [comment]
Here is my previous attempt at getting the std/smtp lib working. Once it's done and control is returned to ncurses I get errors about channels and goroutines still working in the background.

https://github.com/andreas-gone-wild/snackis/blob/b214b0bacf659264a8e8c8471a24bcc2440a3bfe/snackis/smtp.go

And here is the imap code, which has the same issue and on top of that triggers a bug where the library messes up the order of requests and responses to the server which is reported as an issue in the library github. The Python version improves on this code by searching instead, so that's probably something we want to keep doing.

https://github.com/andreas-gone-wild/snackis/blob/37e805ac0df5bd9e618937089f9448fd6dc62d1a/snackis/imap.go

**Comment by joeblew99** [comment]
emersion seems to be the email expert. why not ask him ?
https://github.com/emersion/go-imap#related-projects

**Comment by joeblew99** [comment]
What about if we do this ?
How about we use a build tag to separate out the smtp / imap code using python versus the golang code using golang. Then we can work on both. 
Then can put the code in the non master branches that you referred to above into the Master branch.

**Comment by andreas-gone-wild** [comment]
Aight, I re-introduced the smtp-code using a feature flag, launching with '-smtplib' or setting snackis.SmtpLib =true will use stdlib instead of python. Can't trigger the goroutine/channel problem right now, but much has changed since last time. Having a look at giving imap the same treatment now...

**Comment by andreas-gone-wild** [comment]
Just committed the imap code. Launch with '-imaplib' or set snackis.ImapLib=true to use go-imap. I rewrote the code to search instead of tracking ids and that seems to solve the response-ordering problem as well, fingers crossed. Both Go-versions are currently missing heartbeats which means that the connection may timeout eventually, I'll have a look at that tomorrow.

**Comment by andreas-gone-wild** [comment]
The goroutine/channel heisenbug is unfortunately back for both Smtp/Imap, it looks like the problem has something to do with cgo (which is used for ncurses) in combination with goroutines/channels in the email libraries. I've simplified the code to reconnect on every send/fetch to avoid timeouts and make it easier to isolate the problem, but that's as far as I'm willing to push this now.

**Comment by joeblew99** [comment]
Have not forgotten !
Will pull latest and dig in.
